### ISSUE TITLE
The urlparse module is renamed to urllib.parse in Python 3

### ISSUE THREAD

**Issue by baljeet** [mitsuhiko/flask-oauth#85]
from urlparse import urljoin
ImportError: No module named 'urlparse'

Line 13, flask_oauth.py

Should add try catch for python3 and python 2 compatibility

**Comment by baljeet** [comment]
@mitsuhiko this can be closed!

**Comment by wooohoooo** [comment]
This Error is still present, right? Any way to solve it?

**Comment by edison12a** [comment]
Hey, I'm experiencing this same error on PythonAnywhere!  Any solution please?

**Comment by PierrePaul** [comment]
I guess this can be re-opened?

**Comment by jayrbolton** [comment]
Also having this issue with python 3

**Comment by domdinicola** [comment]
updates on this?

**Comment by not-inept** [comment]
@domdinicola / @jayrbolton / others. I have a workaround solution for myself if you're set on using this library, though it's definitely a hack:
```
import urllib.parse as urlparse
import sys
sys.modules["urlparse"] = urlparse
sys.modules["urllib"] = urlparse
from flask_oauth import OAuth
```

This problem seems to originate from python3 shuffling things around. I'm currently looking at other libraries like authlib as an oauth replacement, but this one has always been nice, so I've also filed https://github.com/mitsuhiko/flask-oauth/issues/96, this shouldn't be too hard to fix at anyrate.

**Comment by not-inept** [comment]
I missed it a few minutes ago, but it looked like this library was marked unmaintained a few months ago:
```
Unmaintained
Flask-OAuth is currently unmaintained. If you want to add OAuth support to your Flask website, we recommend using Flask-Dance instead, which is actively maintained.
```

**Comment by domdinicola** [comment]
@not-inept Thanks a lot!
